QA  fixes
QA notes:

* [31/12/2025] [v0.1.1]: .webp format inference seems not to be working on collab, or I can't visualize. Actually it's just a visualization problem probably since I can't also visualize the original image, meaning that .webpg format is the problem. Maybe the output image always has to be .jpg, meaning it is always converted to .jpg ?

* [31/12/2025] [v0.1.1]: Bounding boxes are thin for big images, as well as the label. Actually I'm going to check if they are also thin for small images. for small images they are also thin but less thin. We would need to improve this aspect by making the labels and bounding boxes a little bit thicker, plus also taking into account the final size of the images. If the final size of the image is 1080x1080 it's not the same thing as 640x640 and therefore the bounding box thickness should change. This is a frontend design decision. It can be changed in the future.

* [31/12/2025] [v0.1.1]: En model.explain estaría bien tener la posibilidad de poner una lista de métodos "method=["eigencam","gradcam"]".

* [31/12/2025] [v0.1.1]: De manera general los métodos en model.explain no funcionan bien o requiren de un poco más de trabajo para estar listos. Tampoco está claro que funcionen igual de bien para yolo8 vs legacy model. El único que realmente pinta la persona parece que es gradcam en yolo8. En mi opinión hay que hacer notar que esto es experimental y está en constante evolución. Dejarlo claro en comentarios del código, así como en la página de documentatción títulado "Explainability (XAI)".

* [31/12/2025] [v0.1.1]: ERROR USANDO TILING:
TypeError                                 Traceback (most recent call last)
/tmp/ipython-input-3721201379.py in <cell line: 0>() 2 3 model = LIBREYOLO("libreyolo8n.pt", size="n")----> 4 results = model("/content/image.jpg", save=True, tiling=True,ouput_path="/tiling1/")
      5
      6 TypeError: LIBREYOLO8.__call__() got an unexpected keyword argument 'tiling'

* [31/12/2025] [v0.1.1]: When save is true, it should generate a folder with every tile as well as the final image as well as a special image which will have the lines that delimit the tiles that compose the final image, so that engineers can visualize.

* [31/12/2025] [v0.1.1]: I don't like the name of the model yolo X, it is inconsistent with the other two. It should be libreyoloXnano, libreyoloXtiny, libreyoloXs, libreyoloXm, libreyoloXl, libreyoloXx in my opinon. Currently this is what we have for auto downlnoad: model8 = LIBREYOLO("libreyolo8n.pt", size="n")
model11 = LIBREYOLO("librelegacy modeln.pt", size="n")
modelX = LIBREYOLO("yolox_s.pt", size="s"). I don't know the implications of changing this name, maybe we need to change the name of the 6 files in the CDN as well?